### ISSUE TITLE
using custom code generators does not work in 0.6.6

### ISSUE THREAD

**Issue by hedron-interactive** [thesamet/sbt-protoc#51]
Demonstrated here:
https://github.com/hedron-interactive/troubleshooting/commit/a4bb25c2d295d1ddc7b1f82def668f63c2fd8715

Observation:
sbt-protoc custom generator support appears to carry a sbt 1.0 version dependency. Being new to sbt and the sbt-protoc plugin I decided to closely follow the example found here: https://github.com/thesamet/sbt-protoc/blob/master/examples/custom-gen/project/MyGenerator.scala. However, my project no longer loads after adding the generator source to my project directory. SBT is unable to resolve the scalapb package. Error captured below for context:

[error] bad symbolic reference. A signature in DescriptorPimps.class refers to term Scalapb
[error] in package com.trueaccord.scalapb which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling DescriptorPimps.class.
[error] one error found
[error] (compile:compileIncremental) Compilation failed

Caveats:
The issue does not repro in version 0.7.0-rc7. See here:
https://github.com/hedron-interactive/troubleshooting/commit/8c09096ac05d660084c4ea549cc4497e5d2e9cce

**Comment by thesamet** [comment]
Yeah, I was able to reproduce this. Is updating to 0.7.0 an acceptable solution for you?

**Comment by xuwei-k** [comment]
duplicate ? https://github.com/thesamet/sbt-protoc/issues/45

**Comment by hedron-interactive** [comment]
That is a perfectly reasonable solution. @xuwei-k yes this appears to be a duplicate - thanks for spotting that.
