### ISSUE TITLE
examples/custom-gen does not work with sbt 0.13.16

### ISSUE THREAD

**Issue by xuwei-k** [thesamet/sbt-protoc#45]
```
[info] Compiling 1 Scala source to /home/travis/build/xuwei-k/sbt-protoc/examples/custom-gen/project/target/scala-2.10/sbt-0.13/classes...
[info] 'compiler-interface' not yet compiled for Scala 2.10.6. Compiling...
[info]   Compilation completed in 8.315 s
[error] bad symbolic reference. A signature in DescriptorPimps.class refers to term Scalapb
[error] in package com.trueaccord.scalapb which is not available.
[error] It may be completely missing from the current classpath, or the version on
[error] the classpath might be incompatible with the version used when compiling DescriptorPimps.class.
[error] one error found
[error] (compile:compileIncremental) Compilation failed
```

**Comment by thesamet** [comment]
Fixed in 0.7.x.
